// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCfD9hikwf9pF-etk0yPDLG-lnsfhLAU0',
    appId: '1:871618972215:web:54adaf3cc571862f204db2',
    messagingSenderId: '871618972215',
    projectId: 'clicktravel-f2302',
    authDomain: 'clicktravel-f2302.firebaseapp.com',
    databaseURL: 'https://clicktravel-f2302-default-rtdb.firebaseio.com',
    storageBucket: 'clicktravel-f2302.appspot.com',
    measurementId: 'G-RJYJ7BR39R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhyb0byFldMdmPNn9cQyhzAZfXYDYel6Q',
    appId: '1:871618972215:android:ce8048854c04b47c204db2',
    messagingSenderId: '871618972215',
    projectId: 'clicktravel-f2302',
    databaseURL: 'https://clicktravel-f2302-default-rtdb.firebaseio.com',
    storageBucket: 'clicktravel-f2302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8NmhD70uMKP9p0nxN9XpEVXH8qO8KmfY',
    appId: '1:871618972215:ios:26386653726f14c6204db2',
    messagingSenderId: '871618972215',
    projectId: 'clicktravel-f2302',
    databaseURL: 'https://clicktravel-f2302-default-rtdb.firebaseio.com',
    storageBucket: 'clicktravel-f2302.appspot.com',
    iosClientId: '871618972215-16qcbglsdjpppqu3kvrlnic1e222pq5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.sprint04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8NmhD70uMKP9p0nxN9XpEVXH8qO8KmfY',
    appId: '1:871618972215:ios:26386653726f14c6204db2',
    messagingSenderId: '871618972215',
    projectId: 'clicktravel-f2302',
    databaseURL: 'https://clicktravel-f2302-default-rtdb.firebaseio.com',
    storageBucket: 'clicktravel-f2302.appspot.com',
    iosClientId: '871618972215-16qcbglsdjpppqu3kvrlnic1e222pq5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.sprint04',
  );
}
